// ICAO → [IATA, 中文名, 英文名] — 涵蓋本份資料 23 家 + 常用航空公司
const AIRLINES={
// —— 本份資料出現 ——
AEE:["A3","愛琴海航空","Aegean Airlines","#00508f"],
ANA:["NH","全日空","All Nippon Airways","#1e50a2"],
ANZ:["NZ","紐西蘭航空","Air New Zealand","#1a1a1a"],
AXM:["AK","亞洲航空","AirAsia","#e60012"],
CAL:["CI","中華航空","China Airlines","#d94f70"],
CPA:["CX","國泰航空","Cathay Pacific","#006564"],
CXA:["MF","廈門航空","Xiamen Airlines","#0068b7"],
DAC:["DA","德安航空","Daily Air","#e87722"],
ETD:["EY","阿提哈德航空","Etihad Airways","#bd8b13"],
EVA:["BR","長榮航空","EVA Air","#00954d"],
IBE:["IB","伊比利亞航空","Iberia","#d7192d"],
ICE:["FI","冰島航空","Icelandair","#003897"],
JJA:["7C","濟州航空","Jeju Air","#f47216"],
JST:["JQ","捷星航空","Jetstar Airways","#ff5115"],
LNI:["JT","獅子航空","Lion Air","#d3122e"],
MAS:["MH","馬來西亞航空","Malaysia Airlines","#cc2229"],
PAL:["PR","菲律賓航空","Philippine Airlines","#00296b"],
RYR:["FR","瑞安航空","Ryanair","#073590"],
SJX:["JX","星宇航空","STARLUX Airlines","#a98e5e"],
TGW:["TR","酷航","Scoot","#ffb700"],
TTW:["IT","台灣虎航","Tigerair Taiwan","#f36f21"],
TWB:["TW","德威航空","T'way Air","#ce0e2d"],
VOE:["V7","沃洛泰航空","Volotea","#a6093d"],
// —— 台灣 ——
MDA:["AE","華信航空","Mandarin Airlines","#d94f70"],
UIA:["B7","立榮航空","UNI Air","#f68b1f"],
// —— 東北亞 ——
JAL:["JL","日本航空","Japan Airlines","#bc0018"],
ADO:["HD","AIR DO","AIR DO"],
SFJ:["7G","星悅航空","StarFlyer"],
SKY:["BC","天馬航空","Skymark Airlines"],
APJ:["MM","樂桃航空","Peach Aviation","#82288c"],
JJP:["GK","捷星日本","Jetstar Japan"],
JTA:["NU","日本越洋航空","Japan Transocean Air"],
FDA:["JH","富士夢幻航空","Fuji Dream Airlines"],
IBX:["FW","IBEX 航空","IBEX Airlines"],
KAL:["KE","大韓航空","Korean Air","#0f8ec7"],
AAR:["OZ","韓亞航空","Asiana Airlines","#c81432"],
JNA:["LJ","真航空","Jin Air"],
ABL:["BX","釜山航空","Air Busan"],
ASV:["RS","首爾航空","Air Seoul"],
ESR:["ZE","易斯達航空","Eastar Jet"],
TZP:["ZG","ZIPAIR","ZIPAIR Tokyo"],
// —— 中港澳 ——
CCA:["CA","中國國際航空","Air China","#e10600"],
CES:["MU","中國東方航空","China Eastern Airlines","#003580"],
CSN:["CZ","中國南方航空","China Southern Airlines","#008ecf"],
CHH:["HU","海南航空","Hainan Airlines"],
CSZ:["ZH","深圳航空","Shenzhen Airlines"],
CQH:["9C","春秋航空","Spring Airlines"],
DKH:["HO","吉祥航空","Juneyao Air"],
CSH:["FM","上海航空","Shanghai Airlines"],
CDG:["SC","山東航空","Shandong Airlines"],
CSC:["3U","四川航空","Sichuan Airlines"],
HDA:["KA","國泰港龍航空","Cathay Dragon"],
CRK:["HX","香港航空","Hong Kong Airlines"],
HKE:["UO","香港快運航空","HK Express","#6d2077"],
AMU:["NX","澳門航空","Air Macau","#00747a"],
GCR:["GS","天津航空","Tianjin Airlines"],
// —— 東南亞 ——
SIA:["SQ","新加坡航空","Singapore Airlines","#002663"],
SLK:["MI","勝安航空","SilkAir"],
JSA:["3K","捷星亞洲航空","Jetstar Asia"],
THA:["TG","泰國國際航空","Thai Airways","#6b3fa0"],
AIQ:["FD","泰國亞洲航空","Thai AirAsia"],
TAX:["XJ","泰國亞洲航空 X","Thai AirAsia X"],
NOK:["DD","皇雀航空","Nok Air"],
TLM:["SL","泰國獅子航空","Thai Lion Air"],
BKP:["PG","曼谷航空","Bangkok Airways"],
HVN:["VN","越南航空","Vietnam Airlines","#00599f"],
VJC:["VJ","越捷航空","VietJet Air","#ec1c24"],
BAV:["QH","越竹航空","Bamboo Airways"],
GIA:["GA","嘉魯達印尼航空","Garuda Indonesia","#175aa5"],
CTV:["QG","連城航空","Citilink"],
BTK:["ID","巴澤航空","Batik Air"],
SJY:["SJ","三佛齊航空","Sriwijaya Air"],
AWQ:["QZ","印尼亞洲航空","Indonesia AirAsia"],
CEB:["5J","宿霧太平洋航空","Cebu Pacific","#ffd200"],
APG:["Z2","菲律賓亞洲航空","AirAsia Philippines"],
MXD:["OD","馬來西亞巴澤航空","Batik Air Malaysia"],
FFM:["FY","飛螢航空","Firefly"],
XAX:["D7","亞洲航空 X","AirAsia X"],
MMA:["8M","緬甸國際航空","Myanmar Airways International"],
RBA:["BI","汶萊皇家航空","Royal Brunei Airlines"],
KHV:["K6","柬埔寨吳哥航空","Cambodia Angkor Air"],
LAO:["QV","寮國航空","Lao Airlines"],
// —— 大洋洲 ——
QFA:["QF","澳洲航空","Qantas","#e0001b"],
VOZ:["VA","維珍澳洲航空","Virgin Australia"],
RXA:["ZL","雷克斯航空","Rex Airlines"],
FJI:["FJ","斐濟航空","Fiji Airways"],
ANG:["PX","新幾內亞航空","Air Niugini"],
// —— 南亞 ——
AIC:["AI","印度航空","Air India"],
IGO:["6E","靛藍航空","IndiGo"],
ALK:["UL","斯里蘭卡航空","SriLankan Airlines"],
PIA:["PK","巴基斯坦國際航空","Pakistan International Airlines"],
BBC:["BG","孟加拉航空","Biman Bangladesh Airlines"],
// —— 中東 ——
UAE:["EK","阿聯酋航空","Emirates","#d71920"],
QTR:["QR","卡達航空","Qatar Airways","#5c0632"],
SVA:["SV","沙烏地阿拉伯航空","Saudia"],
GFA:["GF","海灣航空","Gulf Air"],
MSR:["MS","埃及航空","EgyptAir"],
ELY:["LY","以色列航空","El Al"],
THY:["TK","土耳其航空","Turkish Airlines"],
OMA:["WY","阿曼航空","Oman Air"],
FDB:["FZ","杜拜航空","flydubai"],
// —— 歐洲 ——
BAW:["BA","英國航空","British Airways","#075aaa"],
VIR:["VS","維珍航空","Virgin Atlantic"],
DLH:["LH","漢莎航空","Lufthansa","#05164d"],
AFR:["AF","法國航空","Air France","#002157"],
KLM:["KL","荷蘭皇家航空","KLM","#00a1de"],
SWR:["LX","瑞士國際航空","SWISS"],
AUA:["OS","奧地利航空","Austrian Airlines"],
SAS:["SK","北歐航空","SAS Scandinavian Airlines"],
FIN:["AY","芬蘭航空","Finnair"],
ITY:["AZ","義大利ITA航空","ITA Airways"],
TAP:["TP","葡萄牙航空","TAP Air Portugal"],
VLG:["VY","伏林航空","Vueling"],
EZY:["U2","易捷航空","easyJet"],
WZZ:["W6","維茲航空","Wizz Air"],
NAX:["DY","挪威航空","Norwegian Air Shuttle"],
LOT:["LO","波蘭航空","LOT Polish Airlines"],
AFL:["SU","俄羅斯航空","Aeroflot"],
CYP:["CY","賽普勒斯航空","Cyprus Airways"],
EIN:["EI","愛爾蘭航空","Aer Lingus"],
BEL:["SN","布魯塞爾航空","Brussels Airlines"],
CSA:["OK","捷克航空","Czech Airlines"],
// —— 美洲 ——
UAL:["UA","聯合航空","United Airlines","#005daa"],
AAL:["AA","美國航空","American Airlines","#0078d2"],
DAL:["DL","達美航空","Delta Air Lines","#e01933"],
SWA:["WN","西南航空","Southwest Airlines"],
JBU:["B6","捷藍航空","JetBlue"],
ASA:["AS","阿拉斯加航空","Alaska Airlines"],
HAL:["HA","夏威夷航空","Hawaiian Airlines"],
ACA:["AC","加拿大航空","Air Canada"],
WJA:["WS","西捷航空","WestJet"],
AMX:["AM","墨西哥國際航空","Aeroméxico"],
LAN:["LA","智利南美航空","LATAM Airlines"],
GLO:["G3","高爾航空","GOL Linhas Aéreas"],
ARG:["AR","阿根廷航空","Aerolíneas Argentinas"],
AVA:["AV","哥倫比亞航空","Avianca"],
// —— 非洲 ——
ETH:["ET","衣索比亞航空","Ethiopian Airlines"],
SAA:["SA","南非航空","South African Airways"],
KQA:["KQ","肯亞航空","Kenya Airways"],
RAM:["AT","摩洛哥皇家航空","Royal Air Maroc"]
};
